### ISSUE TITLE
how to use the Micro.py engine

### ISSUE THREAD

**Issue by ABugNamedBeetle** [McManning/GLSLRenderEngine#14]
I wants to create a blender rendering engine, so i want to use micro.py as a base for rendering engine.
Please can u explain how to use and get it running. like where to place files.

**Comment by ABugNamedBeetle** [comment]
does this work in 2.91

**Comment by McManning** [comment]
Sorry for the late reply - my day job has been taking up my week. 

I made a minor fix to micro.py so it should be working now. 

For installing:

Drop `micro.py` into your Blender addons folder. Typically something like `C:\Users\<your username>\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons`

In Blender's *Preferences > Add-ons* search for "Foo" and make sure it's enabled:

![enable foo](https://user-images.githubusercontent.com/1057607/103919414-fdbdc900-50dd-11eb-9d9c-e237156cf389.png)

In your scene settings, change the Render Engine to *Foo Renderer*:

![pick render engine](https://user-images.githubusercontent.com/1057607/103919542-22b23c00-50de-11eb-859f-4d5817008c6b.png)

And then finally change your viewport shading to *Material Preview mode* (or Render preview, they're both the same for this engine): 

![viewport shading](https://user-images.githubusercontent.com/1057607/103919685-54c39e00-50de-11eb-9ecf-062882d7e700.png)

Out of the box with the built-in GLSL shader - it should look like the following:

![suzanne example](https://user-images.githubusercontent.com/1057607/103919934-a8ce8280-50de-11eb-925d-79028e19688e.png)

**Comment by McManning** [comment]
I just installed a copy of 2.91 and it looks like it it does end up crashing if you add another mesh while using it as your viewport renderer. So I'm going to need to figure out what's happening there.

**Comment by McManning** [comment]
I added #15 for the crash. You can track progress there. I do know it works as intended on 2.82 if you want to play with it there in the meantime.

**Comment by McManning** [comment]
My latest commit focused on compatibility fixes / enhancements for `micro.py` - so it should work for you now on 2.91. I've also added a handful of example shaders in the `examples` directory specifically for the micro version:

* `micro_minimal` is just a vertex/fragment shader
* `micro_geometry_shader` is a vertex/fragment/geometry shader combo
* `micro_full_pipeline` adds tessellation stages (basic Phong tessellation algorithm) and renders a wireframe through a geometry shader (attached screenshot)

![micro_full_pipeline screenshot](https://user-images.githubusercontent.com/1057607/104397743-68766680-551b-11eb-8735-44b95508d3f6.png)

If you have any other questions - don't hesitate to ask. 

Thanks!
